services:
  app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    command: sh -c "npm run dev"
volumes:
  node_modules:

